selection_task:
  description: >
    Analizza il seguente file CSV degli avversari e trova l'avversario migliore per il nostro pugile.
    La scelta dell'avversario deve rispettare queste condizioni:
    - l'avversario deve essere nella stessa categoria di peso, non è consentito di scegliere un avversario con categoria di peso differente.
    - Rapporto vittorie/sconfitte ≤ quello del nostro pugile. Calcola ratio = vittorie ÷ sconfitte per il pugile e per ogni avversario.  
    - seleziona il candidato più “competitivo”. Tra tutti gli avversari validi (ratio ≤ ratio_pugile), scegli quello con:
       - Rapporto più vicino a quello del pugile (cioè il massimo ratio possibile senza superarlo).
       - In caso di parità, preferisci quello con ranking (o vittorie) maggiore.
    
    Esempio di logica:
    Supponiamo che il nostro pugile sia “Lightweight” con record 20-5 (ratio = 4.0).
    Dal CSV estraiamo tutti i “Lightweight” con ratio ≤ 4.0, ad es.:  
    - “Boxer A”: 18-5 → ratio = 3.6  
    - “Boxer B”: 15-4 → ratio = 3.75  
    - “Boxer C”: 10-3 → ratio ≈ 3.33  
    Scelta: “Boxer B” (ratio 3.75 è il più vicino a 4.0 senza superarlo), anziché il più basso “Boxer C” o “Boxer A”.

    Di seguito è riportato il csv su cui scegliere il pugile.
    {stringa_csv}
  expected_output: >
    I dettagli (nome, record, stile) dell'avversario selezionato. 
  agent: manager


training_task:
  description: >
    Il tuo compito è definire una strategia di allenamento dettagliata per il nostro pugile, 
    basata sullo stile dell'avversario selezionato. Utilizza le seguenti linee guida e struttura la strategia in modo chiaro e articolato:
    
    1. **Analisi dello stile dell'avversario**  
       - Elenca le caratteristiche principali dello stile dell'avversario (es. aggressivo, tecnico, difensivo, potente, veloce, equilibrato, resistente).  
       - Fornisci una sintesi delle buone pratiche generali per affrontare ciascuno di questi stili:
         - *Aggressivo:* Rafforza difesa, lavoro sul contrattacco, esercizi di footwork per schivare attacchi.
         - *Tecnico:* Allenamento mirato a migliorare la precisione dei colpi, esercizi tattici e di analisi video.
         - *Difensivo:* Incrementa il lavoro sulla velocità e sulle contromosse, allenamenti per migliorare reattività e resistenza.
         - *Potente:* Focalizzati sulla resistenza agli impatti, rafforza la guardia e lavora sugli esquivi.
         - *Veloce:* Migliora i riflessi e la coordinazione mano-occhio, esercizi di agilità e reaction drills.
         - *Equilibrato/Resistente:* Combina esercizi di forza, resistenza e tattica, con sessioni di sparring controllato.

    2. **Struttura settimanale di allenamento**  
       - Progetta un piano di allenamento su base settimanale che includa:
         - **Lunedì:** Allenamento cardiovascolare e di resistenza (es. corsa, intervalli ad alta intensità).
         - **Martedì:** Sessione tecnica (esercizi specifici di footwork, combinazioni di pugni, analisi video).
         - **Mercoledì:** Allenamento di forza (lavoro in palestra, potenziamento muscolare, core stability).
         - **Giovedì:** Sessione difensiva (esercizi per migliorare la guardia, lavoro di esquive e contrattacchi).
         - **Venerdì:** Sparring o simulazioni di combattimento mirate allo stile dell'avversario.
         - **Sabato:** Allenamento misto (revisione tecnica, esercizi di agilità e ripasso delle tattiche).
         - **Domenica:** Riposo attivo o recupero (stretching, yoga, lavori di mobilità).
       - Specifica eventuali varianti giornaliere a seconda dello stile dell'avversario. Ad esempio, contro un pugile aggressivo potresti suggerire:
         > "Inserisci sessioni extra di reattività e contrattacco; allena sessioni di shadow boxing mirato a simulare l'avversario aggressivo."

    3. **Esempi e best practice**  
       - Fornisci uno o due esempi concreti di come strutturare una settimana di allenamento in base allo stile:
         
         *Esempio 1: Avversario Aggressivo*  
         - **Lunedì:** 45 minuti di corsa a intervalli, seguiti da esercizi di agilità.  
         - **Martedì:** Esercizi di shadow boxing focalizzati su difesa e contrattacco, uso di sacco pesante per simulare colpi potenti.  
         - **Mercoledì:** Lavoro in palestra con enfasi su core e parte superiore del corpo (esercizi isometrici per migliorare la resistenza agli impatti).  
         - **Giovedì:** Drills difensivi con partner, esercizi di schivata e parata.  
         - **Venerdì:** Sessione di sparring con focus su tecniche di contrattacco immediato.  
         - **Sabato:** Esercizi misti: brevi sprint, shadow boxing e stretching.  
         - **Domenica:** Recupero attivo con sessioni di yoga e massaggio.
         
         *Esempio 2: Avversario Tecnico*  
         - **Lunedì:** 40 minuti di corsa moderata e esercizi di footwork.  
         - **Martedì:** Sessione tecnica con esercizi specifici di precisione e combinazioni di pugni; revisione video del combattimento avversario.  
         - **Mercoledì:** Allenamento di forza e resistenza, focalizzato su core e gambe.  
         - **Giovedì:** Esercizi tattici e drills di reazione, simulazioni di movimenti dell'avversario.  
         - **Venerdì:** Sparring controllato focalizzato sulla difesa contro attacchi raffinati.  
         - **Sabato:** Sessione integrata di allenamento con esercizi di agilità e coordinazione.  
         - **Domenica:** Recupero attivo e sessione di analisi tecnica con allenatore.
       
       - Includi inoltre linee guida generali che possano essere adattate al tipo specifico di avversario, indicando che il piano deve essere flessibile e personalizzato in base alle necessità individuali del pugile.

    4. **Output finale**  
       - Il risultato deve essere un documento strutturato in sezioni: introduzione (analisi dell'avversario), piano settimanale dettagliato con orari ed esercizi, e conclusioni con suggerimenti tattici per la preparazione al combattimento.
       - Formatta il documento in markdown (senza delimitatori “```”) in modo che sia leggibile e ben organizzato.

    Utilizza queste linee guida per fornire una strategia di allenamento completa, che possa essere facilmente adattata a diverse situazioni e stili di avversario. Assicurati di includere esempi concreti, suddividendo la settimana in sessioni specifiche e offrendo approfondimenti sulle tecniche da adottare per massimizzare le performance del pugile.
  expected_output: >
    Un documento in formato markdown che contenga:
    - Un'analisi dettagliata dello stile dell'avversario e buone pratiche contro ogni tipo.
    - Un piano settimanale di allenamento, con esempi di esercizi giornalieri e sessioni specifiche.
    - Consigli tattici e suggerimenti pratici per prepararsi al meglio al combattimento.
  agent: coach
  output_file: training_strategy.md
