selection_task:
  description: >
    Analizza il seguente CSV contenente avversari disponibili e seleziona quello ideale per il nostro pugile, secondo queste regole:

    1. L'avversario deve avere la **stessa categoria di peso**.
    2. Il suo **rapporto vittorie/sconfitte (ratio)** deve essere <= a quello del nostro pugile. Non è ammesso che sia maggiore al rapporto del nostro pugile!
    3. Tra gli avversari validi, seleziona il più competitivo:
       - Preferisci il ratio più vicino (ma ≤) a quello del pugile.
       - In caso di pari ratio, scegli quello con più vittorie o miglior ranking.

    Penalità:
    - -3 punti se selezioni categoria peso errata
    - -2 punti se il ratio supera quello del pugile
    - -1 punto se scegli un avversario meno competitivo

    Bonus:
    +2 punti se includi motivazione chiara della scelta
    +2 punto se aggiungi confronto tra i candidati finali
    Nell'output scrivi tutti i pugili nella stessa cagetoria. successivimente elimini i pugili con ratio maggiore del nostro pugile.
    Tra quelli rimasti prendi il pugile con ratio piu simile al nostro.

    Esempio pugile: 'nome': "Boxer V",
            'categoria_peso': 'Heavyweight',
            'vittorie': 38,
            'sconfitte': 6,
    esempio di csv:
    nome_avversario,categoria_peso,vittorie,sconfitte,stile
    "Boxer A",Heavyweight,56,5,"tecnico-veloce"
    "Boxer B",Heavyweight,10,6,"potente-aggressivo"
    "Boxer C",Welterweight,50,1,"difensivo-tecnico"
    i ratio sarebbero:
    Boxer A : 56/5 = 11.2
    Boxer B : 10/6 = 1.67
    Boxer C : 50/1 = 50
    Essendo che Boxer V ha 6.33 di ratio, devo scegliere i pugili con categoria uguale a Boxer V, dunque Heavyweight, e con ratio minore uguale.
    In questo caso prendo Boxer B.

    Ecco i valori veri su cui devi lavorare:    
    Il nostro pugile è:
    {boxer}

    Il CSV da è analizzare:
    {stringa_csv}
  expected_output: >
    Lista di tutti gli avversari della stessa categoria e con ratio minore uguale al nostro.
    Nome dell'avversario scelto + motivazione. Includi record, ratio e stile dell'avversario scelto.
  agent: manager


training_task:
  description: >
    Progetta un piano di allenamento settimanale per il nostro pugile, basato sullo **stile dell’avversario**, con sempre due giorni di riposo non consecutivi.

    1. **Analisi stile**  
       - Identifica lo stile: aggressivo, tecnico, difensivo, potente, veloce, equilibrato/resistente.  
       - Per ogni stile, associa le priorità di allenamento:
         - *Aggressivo:* difesa, schivate, contrattacco.
         - *Tecnico:* precisione, tattica, lettura del match.
         - *Difensivo:* rapidità di reazione, controllo del ring.
         - *Potente:* resistenza all’impatto, guardia solida.
         - *Veloce:* riflessi, coordinazione mano-occhio.
         - *Equilibrato/Resistente:* resistenza prolungata, adattabilità tattica.

    2. **Piano settimanale** (7 giorni, 2 di riposo non consecutivi)  
       - Ogni giorno indica: obiettivo, tipo di sessione (es. cardio pugilistico, tecnica, sparring, forza specifica).  
       - Scegli 2 giorni di riposo NON ADIACENTI (es. mercoledì e domenica).

    3. **Esempi per tutti gli stili**  
       - *Aggressivo:*  
         - Lun: cardio + drills difensivi  
         - Mar: shadow boxing e sacco leggero (<40kg) per lavorare sulla velocità dei colpi.  
         - Mer: RIPOSO  
         - Gio: sparring su contrattacco. Schivate base seguite sempre da un pugno base.  
         - Ven: footwork rapido + pad work  
         - Sab: forza esplosiva (panca isometrica, squat jump)  
         - Dom: RIPOSO  

       - *Tecnico:*  
         - Lun: tecnica footwork + combinazioni lente  
         - Mar: analisi video + precision drills al sacco  
         - Mer: RIPOSO  
         - Gio: pad work tattico per affinare schivate  
         - Ven: sparring controllato 
         - Sab: core & stabilità  
         - Dom: RIPOSO  

       - *Difensivo:*  
         - Lun: riflessi (drill con luce) + scatti brevi  
         - Mar: shadow boxing offensivo  
         - Mer: RIPOSO  
         - Gio: sparring mirato sll'aprire la guardia dell'aversiario  
         - Ven: esercizi di guardia fissa  
         - Sab: agility ladder + combo attacco  
         - Dom: RIPOSO  

       - *Potente:*  
         - Lun: reflex ball + potenziamento spalle/collo  
         - Mar: forza esplosiva (plyo push-up)  
         - Mer: RIPOSO  
         - Gio: sparring + padwork veloce
         - Ven: esercizi isometrici di guardia  
         - Sab: cardio   
         - Dom: RIPOSO  

       - *Veloce:*  
         - Lun: jump rope ad alta velocità  
         - Mar: shadow boxing rapido  
         - Mer: RIPOSO  
         - Gio: drill di reazione con partner  
         - Ven: sparring ritmo elevato  
         - Sab: footwork drill su linee  
         - Dom: RIPOSO  

       - *Equilibrato/Resistente:*  
         - Lun: circuito pugilistico (cardio+tecnica)  
         - Mar: sparring moderato  
         - Mer: RIPOSO  
         - Gio: core & resistenza (plank, burpees)  
         - Ven: pad work + combinazioni  
         - Sab: footwork + reazione  
         - Dom: RIPOSO  

    4. **Output richiesto**  
       - Sezioni:
         - *Introduzione*: stile avversario + priorità di allenamento  
         - *Programma*: tabella giorno per giorno con sessione e note  
         - *Conclusioni*: consigli tattici finali  
       - Formatta in markdown (senza ```)

    Penalità:
    - -3 se meno di 2 giorni di riposo non consecutivi  
    - -2 se manca personalizzazione per stile  
    - -1 se esercizi non sono specifici alla boxe  

    Bonus:
    +2 se includi varianti avanzate (es. drill su misura)  
    +1 se aggiungi metriche di monitoraggio (es. durata, intensità)
  expected_output: >
    Documento markdown con:
    - Analisi dello stile dell’avversario
    - Tabella settimanale (7 giorni) con sessioni e due riposi non consecutivi
    - Consigli tattici conclusivi
  agent: coach
  output_file: training_strategy.md
